/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("org.springframework.boot:spring-boot-starter-web:2.3.1.RELEASE")
    api("org.springframework.boot:spring-boot-starter-security:2.3.1.RELEASE")
    api("io.jsonwebtoken:jjwt:0.9.1")
    api("javax.validation:validation-api:2.0.1.Final")
    api("org.springframework.boot:spring-boot-starter-data-jpa:2.3.1.RELEASE")
    implementation("com.h2database:h2")
    api("org.assertj:assertj-core:3.16.1")
    api("org.apache.poi:poi-ooxml:4.1.2")
    api("com.google.guava:guava:30.1-jre")
    api("org.springframework.boot:spring-boot-starter-mail:2.2.5.RELEASE")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.3.1.RELEASE")
    testImplementation("org.springframework.security:spring-security-test:5.3.3.RELEASE")
}

group = "com.example"
version = "0.0.1-SNAPSHOT"
description = "Rooms"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
